[package]
name = "adguardlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "AdGuardHome"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "net", "time", "sync", "macros", "signal", "fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
