#!/usr/bin/env python3
"""Builds the blocklist catalogue this server offers at /control/filtering/catalogue.

Four things come together here:

  * **upstream's catalogue** -- names, categories, homepages and addresses,
    generated by AdGuard from their HostlistsRegistry and bundled in their
    client as `client/src/helpers/filters/filters.ts`;
  * **our annotations** -- `scripts/blocklist-notes.json`, the tags and the
    written note for each list, which are this project's and not AdGuard's;
  * **our additions** -- the `_add` section of the same file, lists this
    project carries that upstream's registry does not;
  * **a measurement** of each list, so the size shown beside it is what the
    list actually contains rather than what someone once wrote down.

With `--measure` every list is downloaded and counted, which doubles as the
validation pass: a list that does not answer 200, or that answers with no
rules at all, fails the import rather than being offered to a user who would
then watch it fail to fetch.  Without it the counts already in the committed
catalogue are kept, so the script can be re-run offline after editing a note.

Usage:
    python3 scripts/import-blocklists.py path/to/filters.ts [--measure]
"""

import gzip
import json
import pathlib
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEST = ROOT / "crates/sift-filter/data/blocklists.json.gz"
NOTES = ROOT / "scripts/blocklist-notes.json"

# Every non-country tag a list may carry.  Kept closed so a typo is an error
# rather than a filter chip nobody can ever match; a two-letter tag is a
# country instead, and is checked against the file's own `_countries`.
VOCABULARY = {
    # What it blocks.
    "ads", "trackers", "telemetry", "annoyances", "malware", "phishing",
    "scam", "crypto-mining", "gambling", "adult", "piracy", "bypass",
    "security",
    # Who it is for.
    "starter", "regional", "device", "allowlist",
    # What to expect.
    "strict",
}

# Derived from the measured rule count, never written by hand.
SIZES = [(1_000, "tiny"), (25_000, "small"), (150_000, "medium"), (1_000_000, "large")]

# A line that is neither blank nor a comment is a rule, which is how the
# engine counts them too.
RULE = re.compile(rb"^[ \t]*([!#]|$)")


def size_tag(rules: int) -> str:
    for limit, name in SIZES:
        if rules < limit:
            return name

    return "huge"


def measure(url: str) -> tuple[int, int]:
    """Downloads one list and returns its (status, rule count)."""
    out = subprocess.run(
        ["curl", "-sS", "-L", "--max-time", "120", "-w", "\n%{http_code}", url],
        capture_output=True,
    )
    if out.returncode != 0:
        return 0, 0

    body, _, code = out.stdout.rpartition(b"\n")
    rules = sum(1 for line in body.splitlines() if not RULE.match(line))

    return int(code or 0), rules


def main(argv: list[str]) -> int:
    args = [a for a in argv[1:] if not a.startswith("--")]
    flags = {a for a in argv[1:] if a.startswith("--")}
    if len(args) != 1 or flags - {"--measure"}:
        print(__doc__, file=sys.stderr)
        return 2

    src = pathlib.Path(args[0]).read_text()
    marker = "export default "
    if marker not in src:
        print(f"{args[0]}: not the generated catalogue", file=sys.stderr)
        return 1

    raw = json.loads(src[src.index(marker) + len(marker):].rstrip().rstrip(";"))
    annotations = json.loads(NOTES.read_text())
    countries: dict[str, str] = annotations.get("_countries", {})
    notes = {k: v for k, v in annotations.items() if not k.startswith("_")}

    # Our own lists join upstream's before anything else looks at them, so
    # they are validated, measured and grouped on exactly the same terms.
    entries = {
        i: {
            "name": f["name"],
            "categoryId": f.get("categoryId", "other"),
            "homepage": f.get("homepage", ""),
            "source": f["source"],
        }
        for i, f in raw["filters"].items()
    }
    for i, f in annotations.get("_add", {}).items():
        if i in entries:
            print(f"{i}: added here but already in upstream's catalogue", file=sys.stderr)

            return 1

        entries[i] = {
            "name": f["name"],
            "categoryId": f.get("category_id", "other"),
            "homepage": f.get("homepage", ""),
            "source": f["url"],
        }

    # Counts from the previous build, so an offline re-run keeps them.
    previous = {}
    if DEST.exists():
        previous = {f["id"]: f.get("rules", 0) for f in json.loads(gzip.decompress(DEST.read_bytes()))["filters"]}

    ids = list(entries)
    problems: list[str] = []

    missing = [i for i in ids if i not in notes]
    orphans = [i for i in notes if i not in ids]
    problems += [f"{i}: no entry in {NOTES.name}" for i in missing]
    problems += [f"{i}: in {NOTES.name} but not in the catalogue" for i in orphans]

    for i, n in notes.items():
        tags = set(n.get("tags", []))
        unknown = {t for t in tags - VOCABULARY if not (len(t) == 2 and t.isalpha() and t.islower())}
        if unknown:
            problems.append(f"{i}: unknown tags {sorted(unknown)}")
        undeclared = {t for t in tags if len(t) == 2 and t.isalpha() and t.islower()} - set(countries)
        if undeclared:
            problems.append(f"{i}: country tags {sorted(undeclared)} are not in _countries")
        if not n.get("tags"):
            problems.append(f"{i}: no tags")
        if not n.get("note", "").strip():
            problems.append(f"{i}: no note")

    counts = dict(previous)
    if "--measure" in flags:
        print(f"measuring {len(ids)} lists...", file=sys.stderr)
        with ThreadPoolExecutor(max_workers=6) as pool:
            results = pool.map(measure, (entries[i]["source"] for i in ids))
            for i, (code, rules) in zip(ids, results):
                if code != 200:
                    problems.append(f"{i}: HTTP {code}")
                elif rules == 0:
                    problems.append(f"{i}: downloaded but contains no rules")
                else:
                    counts[i] = rules

    for i in ids:
        if not counts.get(i):
            problems.append(f"{i}: no rule count; run with --measure")

    if problems:
        print(f"{len(problems)} problem(s):", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)

        return 1

    filters = [
        {
            "id": i,
            "name": entries[i]["name"],
            "category_id": entries[i]["categoryId"],
            "homepage": entries[i]["homepage"],
            "url": entries[i]["source"],
            "rules": counts[i],
            "tags": sorted({*notes[i]["tags"], size_tag(counts[i])}),
            "note": notes[i]["note"],
        }
        for i in ids
    ]

    # Country tags are listed separately: the interface draws them as flags in
    # their own row, and a filter bar with every country mixed into it reads
    # as noise.
    used = {t for f in filters for t in f["tags"]}
    out = {
        "categories": [{"id": cid} for cid in raw["categories"]],
        "tags": sorted(used - set(countries)),
        "countries": {c: n for c, n in sorted(countries.items()) if c in used},
        "filters": sorted(filters, key=lambda f: (f["category_id"], f["name"].lower())),
    }

    blob = json.dumps(out, ensure_ascii=False, separators=(",", ":")).encode()
    # mtime=0 so the same input produces the same bytes on every machine.
    DEST.write_bytes(gzip.compress(blob, 9, mtime=0))

    print(
        f"{len(filters)} lists, {len(out['categories'])} categories, "
        f"{len(out['tags'])} tags, {len(out['countries'])} countries "
        f"-> {DEST.relative_to(ROOT)} ({DEST.stat().st_size} bytes)"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
